-- Vezne Kasa Sayımı (M- Vezne Para Say) için Tablolar ve Saklı Yordamlar (Stored Procedures)
-- Tekrar çalıştırılabilir yapı: IF OBJECT_ID ... CREATE, CREATE OR ALTER PROCEDURE

IF OBJECT_ID('dbo.TODVZ_VEZNE_PARA_SAYIM', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.TODVZ_VEZNE_PARA_SAYIM (
    SAYIM_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TARIH DATE NOT NULL,
    SAAT VARCHAR(10) NULL,
    VEZNE_ID INT NOT NULL,
    VEZNE_KODU VARCHAR(50) NULL,
    VEZNE_ADI VARCHAR(150) NULL,
    KULLANICI_ID INT NULL,
    KULLANICI_ADI VARCHAR(150) NULL,
    ACIKLAMA VARCHAR(500) NULL,
    GENEL_DURUM VARCHAR(50) NULL,
    COUNTS_JSON NVARCHAR(MAX) NULL,
    KAYIT_TARIHI DATETIME NOT NULL DEFAULT GETDATE()
  );
END;
GO

IF OBJECT_ID('dbo.TODVZ_VEZNE_PARA_SAYIM_SATIRI', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.TODVZ_VEZNE_PARA_SAYIM_SATIRI (
    SATIR_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    SAYIM_ID INT NOT NULL,
    PARA_ID INT NOT NULL,
    PARA_KODU VARCHAR(20) NOT NULL,
    PARA_ADI VARCHAR(100) NULL,
    KASA_BAKIYESI FLOAT NOT NULL DEFAULT 0,
    SAYILAN_TUTAR FLOAT NOT NULL DEFAULT 0,
    FARK FLOAT NOT NULL DEFAULT 0,
    TOPLAM_ADET INT NOT NULL DEFAULT 0,
    KUPURLER_JSON NVARCHAR(MAX) NULL,
    CONSTRAINT FK_TODVZ_VEZNE_PARA_SAYIM FOREIGN KEY (SAYIM_ID) REFERENCES dbo.TODVZ_VEZNE_PARA_SAYIM(SAYIM_ID) ON DELETE CASCADE
  );
END;
GO

-- 1. Sayım Başlığı Kaydetme Prosedürü
CREATE OR ALTER PROCEDURE dbo.SODVZ_VEZNE_PARA_SAYIM_KAYDET
  @SAYIM_ID INT = NULL OUTPUT,
  @TARIH DATE,
  @SAAT VARCHAR(10) = NULL,
  @VEZNE_ID INT,
  @VEZNE_KODU VARCHAR(50) = NULL,
  @VEZNE_ADI VARCHAR(150) = NULL,
  @KULLANICI_ID INT = NULL,
  @KULLANICI_ADI VARCHAR(150) = NULL,
  @ACIKLAMA VARCHAR(500) = NULL,
  @GENEL_DURUM VARCHAR(50) = NULL,
  @COUNTS_JSON NVARCHAR(MAX) = NULL
AS
BEGIN
  SET NOCOUNT ON;

  IF @SAYIM_ID IS NULL OR @SAYIM_ID <= 0
  BEGIN
    INSERT INTO dbo.TODVZ_VEZNE_PARA_SAYIM (
      TARIH, SAAT, VEZNE_ID, VEZNE_KODU, VEZNE_ADI,
      KULLANICI_ID, KULLANICI_ADI, ACIKLAMA, GENEL_DURUM, COUNTS_JSON, KAYIT_TARIHI
    )
    VALUES (
      @TARIH, @SAAT, @VEZNE_ID, @VEZNE_KODU, @VEZNE_ADI,
      @KULLANICI_ID, @KULLANICI_ADI, @ACIKLAMA, @GENEL_DURUM, @COUNTS_JSON, GETDATE()
    );

    SET @SAYIM_ID = SCOPE_IDENTITY();
  END
  ELSE
  BEGIN
    UPDATE dbo.TODVZ_VEZNE_PARA_SAYIM
    SET
      TARIH = @TARIH,
      SAAT = @SAAT,
      VEZNE_ID = @VEZNE_ID,
      VEZNE_KODU = @VEZNE_KODU,
      VEZNE_ADI = @VEZNE_ADI,
      KULLANICI_ID = @KULLANICI_ID,
      KULLANICI_ADI = @KULLANICI_ADI,
      ACIKLAMA = @ACIKLAMA,
      GENEL_DURUM = @GENEL_DURUM,
      COUNTS_JSON = @COUNTS_JSON,
      KAYIT_TARIHI = GETDATE()
    WHERE SAYIM_ID = @SAYIM_ID;

    -- Mevcut satırları temizle, yeni gelenler eklenecek
    DELETE FROM dbo.TODVZ_VEZNE_PARA_SAYIM_SATIRI WHERE SAYIM_ID = @SAYIM_ID;
  END;

  SELECT @SAYIM_ID AS SAYIM_ID;
END;
GO

-- 2. Sayım Satırı Ekleme Prosedürü
CREATE OR ALTER PROCEDURE dbo.SODVZ_VEZNE_PARA_SAYIM_SATIR_EKLE
  @SAYIM_ID INT,
  @PARA_ID INT,
  @PARA_KODU VARCHAR(20),
  @PARA_ADI VARCHAR(100) = NULL,
  @KASA_BAKIYESI FLOAT = 0,
  @SAYILAN_TUTAR FLOAT = 0,
  @FARK FLOAT = 0,
  @TOPLAM_ADET INT = 0,
  @KUPURLER_JSON NVARCHAR(MAX) = NULL
AS
BEGIN
  SET NOCOUNT ON;

  INSERT INTO dbo.TODVZ_VEZNE_PARA_SAYIM_SATIRI (
    SAYIM_ID, PARA_ID, PARA_KODU, PARA_ADI, KASA_BAKIYESI, SAYILAN_TUTAR, FARK, TOPLAM_ADET, KUPURLER_JSON
  )
  VALUES (
    @SAYIM_ID, @PARA_ID, @PARA_KODU, @PARA_ADI, @KASA_BAKIYESI, @SAYILAN_TUTAR, @FARK, @TOPLAM_ADET, @KUPURLER_JSON
  );
END;
GO

-- 3. Sayım Silme Prosedürü
CREATE OR ALTER PROCEDURE dbo.SODVZ_VEZNE_PARA_SAYIM_SIL
  @SAYIM_ID INT
AS
BEGIN
  SET NOCOUNT ON;

  DELETE FROM dbo.TODVZ_VEZNE_PARA_SAYIM_SATIRI WHERE SAYIM_ID = @SAYIM_ID;
  DELETE FROM dbo.TODVZ_VEZNE_PARA_SAYIM WHERE SAYIM_ID = @SAYIM_ID;
END;
GO

-- 4. Sayım Kayıtlarını Listeleme Prosedürü
CREATE OR ALTER PROCEDURE dbo.SODVZ_VEZNE_PARA_SAYIM_LISTELE
  @VEZNE_ID INT = 0,
  @LIMIT INT = 100
AS
BEGIN
  SET NOCOUNT ON;

  SELECT TOP (@LIMIT)
    SAYIM_ID AS sayimId,
    TARIH AS tarih,
    SAAT AS saat,
    VEZNE_ID AS vezneId,
    VEZNE_KODU AS vezneKodu,
    VEZNE_ADI AS vezneAdi,
    KULLANICI_ID AS kullaniciId,
    KULLANICI_ADI AS kullaniciAdi,
    ACIKLAMA AS aciklama,
    GENEL_DURUM AS genelDurum,
    KAYIT_TARIHI AS kayitTarihi
  FROM dbo.TODVZ_VEZNE_PARA_SAYIM
  WHERE (@VEZNE_ID = 0 OR VEZNE_ID = @VEZNE_ID)
  ORDER BY SAYIM_ID DESC;
END;
GO

-- 5. Belirli Bir Sayım Detayını Getirme Prosedürü
CREATE OR ALTER PROCEDURE dbo.SODVZ_VEZNE_PARA_SAYIM_GETIR
  @SAYIM_ID INT
AS
BEGIN
  SET NOCOUNT ON;

  -- Başlık
  SELECT 
    SAYIM_ID AS sayimId,
    TARIH AS tarih,
    SAAT AS saat,
    VEZNE_ID AS vezneId,
    VEZNE_KODU AS vezneKodu,
    VEZNE_ADI AS vezneAdi,
    KULLANICI_ID AS kullaniciId,
    KULLANICI_ADI AS kullaniciAdi,
    ACIKLAMA AS aciklama,
    GENEL_DURUM AS genelDurum,
    COUNTS_JSON AS countsJson,
    KAYIT_TARIHI AS kayitTarihi
  FROM dbo.TODVZ_VEZNE_PARA_SAYIM
  WHERE SAYIM_ID = @SAYIM_ID;

  -- Satırlar
  SELECT 
    SATIR_ID AS satirId,
    SAYIM_ID AS sayimId,
    PARA_ID AS paraId,
    PARA_KODU AS paraKodu,
    PARA_ADI AS paraAdi,
    KASA_BAKIYESI AS kasaBakiyesi,
    SAYILAN_TUTAR AS sayilanTutar,
    FARK AS fark,
    TOPLAM_ADET AS toplamAdet,
    KUPURLER_JSON AS kupurlerJson
  FROM dbo.TODVZ_VEZNE_PARA_SAYIM_SATIRI
  WHERE SAYIM_ID = @SAYIM_ID
  ORDER BY SATIR_ID ASC;
END;
GO
