import {useState} from "react";
import {Alert,Button,Card,Col,Form,Row,Table} from "react-bootstrap";
import {Link} from "react-router-dom";
import {ebelgeService,EbelgeMustahsilIstegi} from "../../services/ebelgeService";

const bugun=()=>new Date().toLocaleDateString("en-CA");
export default function EBelgeMustahsilPage(){
 const [g,setG]=useState<EbelgeMustahsilIstegi>({belgeNo:"",tarih:bugun(),paraBirimi:"TRY",smsKodu:"",smsSaglayiciAdi:"",smsSaglayiciVkn:"",uretici:{vknTckn:"",ad:"",soyad:"",adres:"",il:"",ilce:"",telefon:""},satirlar:[{ad:"Hurda altın",miktar:1,birimKodu:"GRM",birimFiyat:0,stopajOrani:2,stopajKodu:"0003",stopajAdi:"GELİR VERGİSİ S. (MUHTASAR)"}]});
 const [busy,setBusy]=useState(false),[mesaj,setMesaj]=useState(""),[hata,setHata]=useState(""),[onay,setOnay]=useState(false);
 const [gelenler,setGelenler]=useState<any[]>([]);
 const u=(k:string,v:string)=>setG(x=>({...x,uretici:{...x.uretici,[k]:v}}));
 const s=(i:number,k:string,v:string|number)=>setG(x=>({...x,satirlar:x.satirlar.map((r,n)=>n===i?{...r,[k]:v}:r)}));
 const ekle=()=>setG(x=>({...x,satirlar:[...x.satirlar,{ad:"",miktar:1,birimKodu:"C62",birimFiyat:0,stopajOrani:2,stopajKodu:"0003",stopajAdi:"GELİR VERGİSİ S. (MUHTASAR)"}]}));
 const calistir=async(send=false)=>{setBusy(true);setHata("");setMesaj("");try{const r=send?await ebelgeService.mustahsilGonder(g):await ebelgeService.mustahsilDogrula(g);setMesaj(send?`${r.belgeNo} gönderildi. ETTN: ${r.uuid}`:`Şema ve schematron doğrulandı. Net ödeme: ${r.ozet.netOdenecek} TRY`);setOnay(false);}catch(e:any){setHata(e.message||"İşlem başarısız.");}finally{setBusy(false)}};
 const gelenYukle=async()=>{setBusy(true);setHata("");try{setGelenler(await ebelgeService.mustahsilGelen({limit:100,okunanlar:true,islenenler:true}));}catch(e:any){setHata(e.message||"Gelen belgeler alınamadı.");}finally{setBusy(false)}};
 return <div className="container-fluid py-3"><div className="d-flex justify-content-between"><h5>e-Müstahsil Makbuzu</h5><Link to="/e-belge/giden">Giden Kutusu</Link></div>
 {hata&&<Alert variant="danger">{hata}</Alert>}{mesaj&&<Alert variant="success">{mesaj}</Alert>}
 <Card className="mb-3"><Card.Body><fieldset disabled={busy}><Row className="g-2"><Col md={4}><Form.Label>Belge No</Form.Label><Form.Control value={g.belgeNo} onChange={e=>setG({...g,belgeNo:e.target.value.toUpperCase()})} placeholder="MST2026000000001"/></Col><Col md={3}><Form.Label>Tarih</Form.Label><Form.Control type="date" value={g.tarih} onChange={e=>setG({...g,tarih:e.target.value})}/></Col><Col md={5}><Form.Label>Üretici TCKN/VKN</Form.Label><Form.Control value={g.uretici.vknTckn} onChange={e=>u("vknTckn",e.target.value)}/></Col>
 {[["ad","Ad"],["soyad","Soyad"],["telefon","SMS gönderilen telefon"],["il","İl"],["ilce","İlçe"],["adres","Adres"]].map(([k,l])=><Col md={4} key={k}><Form.Label>{l}</Form.Label><Form.Control value={(g.uretici as any)[k]||""} onChange={e=>u(k,e.target.value)}/></Col>)}</Row></fieldset></Card.Body></Card>
 <Card className="mb-3"><Card.Body><h6>SMS doğrulama</h6><Row className="g-2"><Col md={4}><Form.Label>SMS kodu</Form.Label><Form.Control value={g.smsKodu} onChange={e=>setG({...g,smsKodu:e.target.value})}/></Col><Col md={4}><Form.Label>Sağlayıcı adı</Form.Label><Form.Control value={g.smsSaglayiciAdi} onChange={e=>setG({...g,smsSaglayiciAdi:e.target.value})}/></Col><Col md={4}><Form.Label>Sağlayıcı VKN</Form.Label><Form.Control value={g.smsSaglayiciVkn} onChange={e=>setG({...g,smsSaglayiciVkn:e.target.value})}/></Col></Row></Card.Body></Card>
 <Card><Card.Body><Table responsive size="sm"><thead><tr><th>Ürün</th><th>Miktar</th><th>Birim</th><th>Birim fiyat</th><th>Stopaj %</th><th>Stopaj kodu</th><th></th></tr></thead><tbody>{g.satirlar.map((r,i)=><tr key={i}>{[["ad","text"],["miktar","number"],["birimKodu","text"],["birimFiyat","number"],["stopajOrani","number"],["stopajKodu","text"]].map(([k,t])=><td key={k}><Form.Control size="sm" type={t} value={(r as any)[k]} onChange={e=>s(i,k,t==="number"?Number(e.target.value):e.target.value)}/></td>)}<td><Button size="sm" variant="outline-danger" disabled={g.satirlar.length===1} onClick={()=>setG(x=>({...x,satirlar:x.satirlar.filter((_,n)=>n!==i)}))}>Sil</Button></td></tr>)}</tbody></Table>
 <div className="d-flex gap-2"><Button variant="outline-secondary" disabled={busy} onClick={ekle}>Satır ekle</Button><Button disabled={busy} onClick={()=>calistir(false)}>ICE ile doğrula</Button><Button variant="danger" disabled={busy} onClick={()=>setOnay(true)}>Gönderime hazırla</Button></div>
 {onay&&<Alert variant="warning" className="mt-3"><strong>Bu işlem gerçek e-Müstahsil oluşturur ve mali sonuç doğurur.</strong><div className="mt-2"><Button variant="danger" disabled={busy} onClick={()=>calistir(true)}>Evet, ICE'ye gönder</Button><Button className="ms-2" variant="secondary" onClick={()=>setOnay(false)}>Vazgeç</Button></div></Alert>}
 </Card.Body></Card>
 <Card className="mt-3"><Card.Body><div className="d-flex justify-content-between"><h6>Gelen e-Müstahsiller</h6><Button size="sm" disabled={busy} onClick={gelenYukle}>ICE'den getir</Button></div><Table responsive size="sm" className="mt-2"><thead><tr><th>Belge</th><th>ETTN</th><th>Taraflar</th><th>Tarih</th><th>Net</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{gelenler.map((r:any)=><tr key={r.UUID||r.ID}><td>{r.ID||"-"}</td><td className="small">{r.UUID||"-"}</td><td>{r.HEADER?.SUPPLIER_TITLE||r.HEADER?.CUSTOMER_TITLE||"-"}</td><td>{String(r.HEADER?.ISSUE_DATE||"").slice(0,10)}</td><td>{r.HEADER?.PAYABLE_AMOUNT?.['#text']??r.HEADER?.PAYABLE_AMOUNT??"-"}</td><td>{r.STATUS_DESCRIPTION||r.STATUS_CODE}</td><td><Button size="sm" variant="outline-primary" onClick={async()=>{try{await ebelgeService.mustahsilGelenStatu(r.UUID,"Islendi");setMesaj(`${r.ID} işlendi olarak işaretlendi.`);await gelenYukle();}catch(e:any){setHata(e.message)}}}>İşlendi</Button></td></tr>)}{!gelenler.length&&<tr><td colSpan={7} className="text-center text-secondary">Liste henüz ICE'den alınmadı.</td></tr>}</tbody></Table></Card.Body></Card>
 </div>;
}
